### ISSUE TITLE
Feature Request Training Plans

### ISSUE THREAD

**Issue by HCrane** [cvweiss/skillq#16]
It would be awesome to have the Skill Plan Training Feature so it is possible to plan skills ahead! It would also be a nice feature to have a calculation how much small and large skill injectors are needed. Also ich we could paste a fitting and it shows how many skills have to be trained.

**Comment by cvweiss** [comment]
Skill planning is definitely in the works for long term as I have time to do it. Your other suggestions are pretty good too. 

I'll keep this ticket around as an enhancement request for skill planning.

**Comment by xan2622** [comment]
Hi.

It would be convenient to be able to select an item (weapon, ship, module..) and Skillq would list the required skills to be able to use the item. Ideally, there would be a checkbox to filter the list of skills, to only show the ones that the player hasn't trained (the remaining skills).

**Comment by cvweiss** [comment]
I probably won't ever implement skill plans. Sorry. SkillQ is more of a monitoring tool than a planning tool for me. Others are welcome to add to the code of course.
