### ISSUE TITLE
Feature: Accountnames

### ISSUE THREAD

**Issue by HCrane** [cvweiss/skillq#18]
I dont know if it is possible form ESI side but it would be helpful to display the account name in the detail view of any char. I have quite some chars to manage and sometimes i forget where which char is. Just something for some lazy ppl like me :)

**Comment by ficti0n1** [comment]
It's not possible via ESI. No account info will ever show there, including game time, omega status etc.

This would require you giving steve your Account name manually. Not sure he would want this info as it should always remain hidden from anyone but you and CCP.

**Comment by cvweiss** [comment]
As @ficti0n1 said, this is not possible with the current APIs, also, CCP has stated numerous times they will not extend such functionality to the API anymore.
