### ISSUE TITLE
Bug: Incorrect Total SP

### ISSUE THREAD

**Issue by ficti0n1** [cvweiss/skillq#19]
Total SP for a character hasn't updated.

![image](https://user-images.githubusercontent.com/36131270/39707502-85c9b22e-520c-11e8-9935-3b126addf626.png)

![image](https://user-images.githubusercontent.com/36131270/39707602-c9f1c464-520c-11e8-8c7e-afbd34d0a081.png)

This bug appears  on many of my characters. Feel free to 'take control' to test.

Other characters you can test to see the problem:

Aa-a-a-a-a-a-a-a Wad

**Comment by cvweiss** [comment]
The SP reported matches what is provided by the API. Unfortunately, the API isn't updated until a skill completes and/or the character is logged in. I'm not entirely certain on the events required.

I could go the evemon route and calculate what the SP might be, but that's a rabbit hole I don't really want to go down at this time.

Also, interesting name for a character!
