### ISSUE TITLE
Skill Block Graphics somewhat Misleading

### ISSUE THREAD

**Issue by ficti0n1** [cvweiss/skillq#20]
More of an 'enhancement' then a bug

![image](https://user-images.githubusercontent.com/36131270/39743143-ea3fa4f8-5297-11e8-818d-69efb962740c.png)

This suggests the skill is trained to 4 and is going up to 5.

In reality it's at 3 and going to 4 and then to 5

![image](https://user-images.githubusercontent.com/36131270/39743180-09d634da-5298-11e8-8ba6-d207840ce862.png)

Perhaps all untrained/training blocks should show blue?

![image](https://user-images.githubusercontent.com/36131270/39743235-34d777ac-5298-11e8-8c7c-c30d583850f0.png)

If you make a skillq channel on tweetfleet I can post these issues there if you prefer not to have your git clogged up. Or I can not post minor minor things like this at all too.

**Comment by cvweiss** [comment]
I would actually consider this a bug. It isn't visually representing the skill's training properly. I'll need to look at if this is an issue with the api itself or something with skillq.
