### ISSUE TITLE
[Enhancement] Columns dependent on screen resolution

### ISSUE THREAD

**Issue by elite3vil** [cvweiss/skillq#21]
I don't know how much of a pain it would be, but would it be possible to have the number of columns of characters shown, increase with the width of the screen? I can't currently fit all my characters on the screen without scrolling, but have a lot of empty space to the left and right of where they're displayed.

Thanks!

**Comment by cvweiss** [comment]
@elite3vil Just to be sure, you're seeing at least 3 characters per row correct?

**Comment by elite3vil** [comment]
@cvweiss Yeah. Just three per row, with room for probably 5 without being cramped. Like I said I didn't know how much work would be involved, a little scrolling for a while won't kill anyone. 👍

**Comment by ficti0n1** [comment]
As long as 3 chars per row remains the standard. It's very convenient as it matches up with 3 characters per account.

**Comment by cvweiss** [comment]
Can't remain standard and be fluid at the same time. I suppose I could make this an option, but in the meantime it is now fluid.

**Comment by ficti0n1** [comment]
Man this has really ruined the setup I had. :(

**Comment by cvweiss** [comment]
Screwed up the commit, meh, anyhow, this is now an option. The default is 3 per row, but you can set fluidity to max rows per character with the options under Account.
