### ISSUE TITLE
Sorting behaviour not shared between different devices

### ISSUE THREAD

**Issue by justAnotherUserFromTheInternet** [cvweiss/skillq#23]
While the custom sorting order numbers you can set up for each character are shared between devices, the sorting order is always the default one for every new device.

**Comment by cvweiss** [comment]
The settings are based on the initial user that you logged in with. If you've started each device with a different user, they will not share the same settings. Try logging out completely, and then logging back in with the same initial user.

**Comment by cvweiss** [comment]
Closing as non an issue.
