### ISSUE TITLE
Error on Account add

### ISSUE THREAD

**Issue by justindh** [cvweiss/skillq#27]
Receive the following error when adding a character for the first time

`Slim Application Error
The application could not run because of the following error:

Details
Message: Invalid state returned - possible hijacking attempt
File: /var/www/skillq.net/vendor/zkillboard/crestsso/src/CrestSSO.php
Line: 103
Trace
#0 /var/www/skillq.net/vendor/zkillboard/crestsso/src/CrestSSO.php(110): zkillboard\crestsso\CrestSSO->validateStates('dBqZ4rbiFYeduVN...', NULL)
#1 /var/www/skillq.net/view/ccp-callback.php(23): zkillboard\crestsso\CrestSSO->handleCallback('EmTxDNhlsoi0O8j...', 'dBqZ4rbiFYeduVN...', Array)
#2 /var/www/skillq.net/routes.php(94): include('/var/www/skillq...')
#3 [internal function]: {closure}()
#4 /var/www/skillq.net/vendor/slim/slim/Slim/Router.php(200): call_user_func_array(Object(Closure), Array)
#5 /var/www/skillq.net/vendor/slim/slim/Slim/Slim.php(1218): Slim\Router->dispatch(Object(Slim\Route))
#6 /var/www/skillq.net/vendor/slim/slim/Slim/Middleware/Flash.php(86): Slim\Slim->call()
#7 /var/www/skillq.net/vendor/slim/slim/Slim/Middleware/MethodOverride.php(94): Slim\Middleware\Flash->call()
#8 /var/www/skillq.net/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#9 /var/www/skillq.net/vendor/slim/slim/Slim/Slim.php(1167): Slim\Middleware\PrettyExceptions->call()
#10 /var/www/skillq.net/index.php(38): Slim\Slim->run()
#11 /var/www/skillq.net/public/index.php(3): require_once('/var/www/skillq...')
#12 {main}`

**Comment by cvweiss** [comment]
Assuming you've had no further issues. closing.
