### ISSUE TITLE
[Enhancement] Dropdown for Items that a Skill is needed for

### ISSUE THREAD

**Issue by HCrane** [cvweiss/skillq#36]
on the route /itenm/XXX there is a huge list of items that are enabled by level 1-5 of a skill. plaxcing them inside a dropdown menu would add a little bit more oversight to the site.

**Comment by cvweiss** [comment]
I'm not sure what you mean by adding "a little bit more oversight", can you explain please?

**Comment by HCrane** [comment]
sure! For example take this skill:

![image](https://user-images.githubusercontent.com/10025542/41654230-12c7607e-7489-11e8-98f6-608493f5040e.png)

It is required by all ships in the game. If you could add a dropdown for Skill I-V enables this would make the site a bit more compact.

**Comment by cvweiss** [comment]
Ah, a dropdown or accordion might help, I see what you're saying now.
