### ISSUE TITLE
Request: A display to inform that the characters are not training.

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [cvweiss/skillq#37]
On the all Characters screen, It would be nice to have a line of text where the training skill is usually displayed if the character has no active skills training. This line would ideally say something like: "Not Training". This line would, at an easy glance, allow the user to see what skill queues are stopped when they have a large number of characters added to the All characters screen. To stand out a little more, maybe this text could also be a different color than Black.

**Comment by cvweiss** [comment]
I think the lack of a skill training, and the lack of a countdown, is enough to signify that the character is not training. Adding a NO TRAINING attribute would detract for those of who have many alts that are rarely trained.

An alternative to display is if skills are queued up, but not training, then a "Skills Stopped" or something similar might be worthwhile.

Marking as won't fix.
