### ISSUE TITLE
[Feature] Grouping of chars

### ISSUE THREAD

**Issue by HCrane** [cvweiss/skillq#38]
I  have a small SP farm and some "regular" accounts. It would be awesome if i could assing every char a group soit gets displayed seperately. Maybe it would be best and to keep the work as little as possible one could only use predefined groups (SP Farm, Regular, whatever).

**Comment by cvweiss** [comment]
<img width="1092" alt="screen shot 2018-07-15 at 1 18 30 pm" src="https://user-images.githubusercontent.com/739285/42736266-c880b152-8831-11e8-8b84-1b60ba59852c.png">
