### ISSUE TITLE
Feature request: account status and/or account remaining time

### ISSUE THREAD

**Issue by Flux78** [cvweiss/skillq#40]
is it possible to view the account status and/or account remaining omega time?
would be great

**Comment by cvweiss** [comment]
Account status is something that CCP has made **very** clear they will not make available via API. While I could add something that allows you to manually specify you gave x characters y time on their account, that's something that is reliant on the end user and tbh, very error prone. And then I'll get blamed for it when someone eventually gets it wrong.

So, in short, no, this will not be a feature. If, big if, CCP changes their stance and makes this information available via API, then the request can be revisited. Until then, sorry, no.
