### ISSUE TITLE
Incorrect Unallocated skill points

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [cvweiss/skillq#42]
Maybe as a result of the sp compensation that CCP recently gave out, there is a notice of unallocated SP on skillq, even though I have already allocated this sp and have no other unallocated sp on the character.

![sp](https://user-images.githubusercontent.com/31759736/44316345-02379900-a3e0-11e8-831f-aafb91c6b43e.PNG)

**Comment by cvweiss** [comment]
CCP is reporting that value. Have you logged in again _after_ allocating the SP?

**Comment by ALongStringOfNumbers** [comment]
Yes, I have logged in since allocating the SP. When checking on my character in game, it has the same amount of sp as in the image, but there is no sp unallocated

**Comment by cvweiss** [comment]
Can you at least tell me the name of the character in question? Otherwise debugging becomes very difficult. Especially since over 5k characters in the db have 250k unallocated SP, and 100+ characters have 250k unallocated SP and are training Drone Durability V...

**Comment by ficti0n1** [comment]
Also having exactly the same issue. Here are some characters:
ficti0n, Jon Sei

I'm guessing monolith issue though.

**Comment by cvweiss** [comment]
not monolith

The key is missing completely from the api pull when unallocated sp is 0, so it wasn't getting applied

**Comment by cvweiss** [comment]
Thank you @ficti0n1
