### ISSUE TITLE
Search skills

### ISSUE THREAD

**Issue by charliedimaggio** [cvweiss/skillq#44]
I've found myself wanting to find out which of my characters have a skill trained, but there is no easy way to accomplish this. Is this something you can consider adding to skillq?

**Comment by ddavaham** [comment]
You can do this on [LevelV](https://levelv.space) by adding the characters as alts, then creating a skillplan and share the skillplan between your characters

**Comment by cvweiss** [comment]
If you're skill planning, and not just monitoring skills, I recommend Level V.
