### ISSUE TITLE
[Enhancement?] Login page - Overview instead of Character Page

### ISSUE THREAD

**Issue by ficti0n1** [cvweiss/skillq#45]
Upon login you're taken straight to the character page rather then overview. I would guess most use skillq for managing multiple characters and showing overview page on login would be more useful.

**Comment by cvweiss** [comment]
IMO, for SkillQ, it makes more sense to be taken to the character screen of the person you're logging in as, rather than just the overview. It is only 1 click to get to the overview screen anyhow.
