### ISSUE TITLE
Unable to remove my character

### ISSUE THREAD

**Issue by Ionaru** [cvweiss/skillq#46]
I am unable to remove my character from SkillQ.
The error is: `Uncaught SyntaxError: missing ) after argument list` on this line: 
```
<td><span class='pull-right'><a href='#' onClick="verifyRemoval('Cap&#039;n Proton', 92840153); return false;">X</a></span></td>
```

I think the quote (`'`) in my character's name isn't properly being escaped.
![image](https://user-images.githubusercontent.com/3472373/47273560-b7303280-d596-11e8-9cfb-77819315c9cc.png)

I was able to remove the character successfully by editing the HTML and escaping the `'` in my character's name so it looks like this: `verifyRemoval('Cap\'n Proton', 92840153)`.

**Comment by cvweiss** [comment]
OK this hopefully addressees it, I tried to shortcut it earlier, meh

**Comment by Ionaru** [comment]
Looks good, verified 👍
