### ISSUE TITLE
Feature Request SMS Notifications

### ISSUE THREAD

**Issue by D33pfield** [cvweiss/skillq#49]
An option to add a short SMS digest would be pretty nice. Few different things you could do with this I'm sure

**Comment by cvweiss** [comment]
SMS services cost money. I don't, and won't, charge for SkillQ (I don't even display ads), and I eat the cost of the server per month, which really is only about $10. So, I'm going the cheap route here and saying:

Sorry, this feature will not be implemented.

You can always set up a filter with your email service to prioritize and notify on emails from SkillQ.
