### ISSUE TITLE
Wrong SP shown accounts with unallocated SP

### ISSUE THREAD

**Issue by Nahaz** [cvweiss/skillq#51]
It looks like unallocated SP is substracted from total SP. There are some discrepancies besides that but my accounts are showing:
skillQ
4.6m SP, 300k unallocated
ingame
4.9m SP, 300k unallocated

This is true for all my characters.

The other discrepancies are in the region of 30K SP which I can't pinpoint.

**Comment by cvweiss** [comment]
An API is not updated until after you login a character, also apis don't fully reflect the fully trained value of a skill until that skill is completed. I discrepensy of 30k is so minor it isn't even worth looking into.

**Comment by Nahaz** [comment]
But I have logged in on my characters, the problem is that the unallocated SP is subtracted from the actual trained SP

![sp](https://user-images.githubusercontent.com/457154/52142390-d4c26d00-2658-11e9-86b0-5b27784eb2cf.png)
