### ISSUE TITLE
Total Number of Skills in Queue

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [cvweiss/skillq#53]
Is there anyway that the total number of skills currently in the skill queue could be displayed as sometimes I have a bunch of short skills right after each other and so when I check on them I don't have any idea of how many of them have completed besides counting the entire list. Mock image here (I did it on a track pad so it is sort of bad)

![TotNum](https://user-images.githubusercontent.com/31759736/54310530-d3595e00-458f-11e9-8c3e-32305c78b9e6.PNG)

**Comment by cvweiss** [comment]
I would have never figured how to do this without that awesome mock image :P
