### ISSUE TITLE
[Enhancement] free notes

### ISSUE THREAD

**Issue by nullx8** [cvweiss/skillq#66]
would be extremly handy if it would be possible to add a custom note to characters, to be able identifying them or the ingame function.

**Comment by cvweiss** [comment]
<img width="190" alt="image" src="https://github.com/cvweiss/skillq/assets/739285/8ce927ca-d65a-4ae5-bfaa-85fd0acdeb8f">

Click Manage, name them into groups however you'd like:

<img width="124" alt="image" src="https://github.com/cvweiss/skillq/assets/739285/854db7c6-cebf-4a48-a92d-efab18da7a0f">

And at the bottom be sure to sort it however you'd like too.
