### ISSUE TITLE
Ability to see current skill levels and previous skills in training queue?

### ISSUE THREAD

**Issue by Mo0rBy** [cvweiss/skillq#67]
I'm currently away from my battle station and so I have used my phone to check on my skill training.

I was thinking that it would be useful to be able to see previously trained skills, or to just see all your skills at their current level.

It's nice to see what I am training now and what I have planned, but I can't remember what I have trained previously.

**Comment by cvweiss** [comment]
skillq has always had this capability, you can see your current skill queue, and then below that all of the skill levels you have already trained

scroll down :)

**Comment by Mo0rBy** [comment]
Oh yes, you can see current skills, my bad.

For previous skills I meant more like a history. So for the future skills, you can see them all in order, what about previous skills and the history of what you have trained, so you can see the order in which you trained them as well.

I'm not even sure if this is a capability that is possible with ESI.

**Comment by cvweiss** [comment]
Unfortunately skill training history is not in the ESI.

**Comment by Mo0rBy** [comment]
Well, case closed then.

Thanks for pointing me to the current skills. I think it might be better to have it in a different location, some people (like me) have a very long skill queue (2+ years), so it's quite annoying to have to scroll all the way down to get there.

Anyway, thanks!
